import type { Metadata } from "next";
import { Header } from "@/components/shared/Header";

export const metadata: Metadata = {
  title: "Next | Главная страница",
  description: "Generated by create next app",
};

export default function HameLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (


    <>
      <Header />
      <main className="min-h-screen">
        {children}
        {modal}
      </main>
    </>


  );
}
