import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared/Header";

const geistNunito = Nunito({
  weight: ["400","500","600", "700","800","900"],
  variable: "--font-nunito",
  subsets: ["cyrillic"],
});


export const metadata: Metadata = {
  title: "Next | Главная страница",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistNunito.variable} antialiased`}
      >
        <Header />
        <main className="min-h-screen">
          {children}
        </main>

      </body>
    </html>
  );
}
