import type {Metadata} from "next";
// type Params = Promise<{ id: string }>


export const metadata: Metadata = {
  title: "Next | продукт ",
  description: "Generated by create next app",
};

export default async function ProductPage( ){

  return (
    <div>ProductPage</div>
  )
}